### ISSUE TITLE
Time Elapsed count up timer runs while "Destination Doesn't have enough space" user prompt is present

### ISSUE THREAD

**Issue by callan752** [jgric2/Brutal-Copy-Release-Installer-#2]
### Description
---
Time Elapsed count up Runs While "Destination Doesn't have enough space" warning is present

### User Story
---
When copying to a location that doesn't have enough space, a "Destination Doesn't have enough space" warning appears but the Time Elapsed counter continues counting up. I'm thinking this is likely not intended behavior that would skew copy times high if while this elapsed time count up is running the user frees up space and then clicks continue. 

### Expected Action
---
Stop Elapsed time count up when free space or other user prompting error is present that halts copying

**Comment by jgric2** [comment]
Thank you! I have applied a fix and should be released in the update either today or tomorrow.

**Comment by jgric2** [comment]
should be good now @callan752
