### ISSUE TITLE
Unable to Activate Licence.

### ISSUE THREAD

**Issue by ACCESSDENIIED** [jgric2/Brutal-Copy-Release-Installer-#5]
I've been using the program for about 2 months now. After ~30 days I had a prompt to activate with the option to provide feedback to extend the duration of the trial. I provided feedback which successfully allowed another 30 days. Following this the same prompt to activate the license popped up again but I'm unable to proceed any further and there is no option to provide feedback or to purchase.

Cheers!

**Comment by jgric2** [comment]
Hello again!

Please send me an email at James@Limintel.com
and I will sort this out for you

Regards
James

**Comment by ACCESSDENIIED** [comment]
Done :)
